import Head from 'next/head'
import ClientRole from '../src/components/homepage/clientRole'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-6xl block m-auto pb-24 md:pb-36">
        <ClientRole />
    </div>
    </div>
  )
}
